"""Simulator validation on the validation seasons: compare against realized frequencies, Baseline 1
and Model 1's direct classifier.

Run with `uv run python -m src.sim.run_simulator`. Uses the same walk-forward folds, rating
settings (re-derived, not re-tuned) and validation seasons as `src.models.run_model1`; the holdout
and forward-test seasons are never loaded.
"""

from __future__ import annotations

import time
from pathlib import Path

import pandas as pd

from src.config import load_config
from src.models import run_model1 as model1_run
from src.models.evaluation import calibration_table, plot_calibration
from src.models.model1 import FULL_COLUMNS, WIN_COLUMNS
from src.models.model1 import walk_forward_predictions as model1_predictions
from src.models.reporting import LABEL_NAMES, markdown_table, results_table, score_model
from src.sim.tournament import estimate_residual_sigma, event_rng, simulate_event, simulate_events

LABELS = model1_run.LABELS


def simulate_predictions(
    features: pd.DataFrame,
    rounds: pd.DataFrame,
    folds: list,
    sim_settings: dict,
    cut_mode: str,
    seed: int,
) -> dict[str, pd.DataFrame]:
    """Simulated win/top10/made_cut predictions per validation fold, shaped for `score_model`.

    Sigma is estimated on each fold's training seasons only, matching the walk-forward folds used
    for Baseline 1 and Model 1.
    """
    parts = {label: [] for label in LABELS}
    for train_seasons, test_season in folds:
        train = features[features["season"].isin(train_seasons)]
        train_rounds = rounds[rounds["season"].isin(train_seasons)]
        sigma = estimate_residual_sigma(train, train_rounds)

        test = features[features["season"] == test_season]
        simulated = simulate_events(
            test,
            sigma,
            sim_settings["n_sims"],
            seed,
            cut_mode,
            sim_settings["fallback_cut_fraction"],
        )
        # simulate_events' probability columns (win, top10, made_cut) share their names with the
        # actual outcome columns being merged in, so rename before merging to avoid a collision.
        simulated = simulated.rename(columns={label: f"{label}_p" for label in LABELS})
        merged = simulated.merge(
            test[["tournament_id", "player_id", "season", "no_history", *LABELS]],
            on=["tournament_id", "player_id"],
        )
        for label in LABELS:
            defined = merged[merged[label].notna()].copy()
            defined["event"] = defined["tournament_id"]
            defined["y"] = defined[label].astype(int)
            defined["p"] = defined[f"{label}_p"]
            defined["p_naive"] = float(train[label].astype(float).mean())
            defined["has_history"] = defined["no_history"] == 0
            keep = [
                "season",
                "tournament_id",
                "event",
                "player_id",
                "y",
                "p",
                "p_naive",
                "has_history",
            ]
            parts[label].append(defined[keep])
    return {label: pd.concat(frames, ignore_index=True) for label, frames in parts.items()}


def time_ten_thousand_sims(features: pd.DataFrame, sigma: float) -> tuple[int, float]:
    """How long 10,000 simulations of the largest validation-season field take."""
    sizes = features[features["is_standard_event"]].groupby("tournament_id").size()
    biggest = features[features["tournament_id"] == sizes.idxmax()]
    rating = biggest["rating"].fillna(0.0).to_numpy()
    start = time.perf_counter()
    simulate_event(rating, sigma, 10000, event_rng(0, "timing"), cut_keep=len(rating) // 2)
    return len(rating), time.perf_counter() - start


def build_report(
    config, folds, half_life, shrink, rows, fraction_rows, field_size, seconds, sigma
) -> str:
    validation = config["splits"]["validation_seasons"]
    samples, seed = config["evaluation"]["bootstrap_samples"], config["evaluation"]["seed"]
    fold_lines = "\n".join(f"- validate {test}: fit on seasons {train}" for train, test in folds)
    fraction_table = markdown_table(
        pd.DataFrame(
            [
                {
                    "label": LABEL_NAMES[r["label_key"]],
                    "log_loss": r["log_loss"],
                    "diff_vs_naive": r["log_loss_delta"],
                }
                for r in fraction_rows
            ]
        )
    )
    return f"""# Simulator: validation report

Generated by `uv run python -m src.sim.run_simulator` from `config/config.yaml`.
Validation seasons {validation}. The holdout ({config["splits"]["holdout_seasons"]}) and the
forward-test ({config["splits"]["forward_test_seasons"]}) seasons were **not** loaded or looked at.

The simulator draws each round's field-relative score as `-rating + Normal(0, sigma)`, where
`rating` is Model 1's as-of field-adjusted rating (half-life {half_life:.0f} days, shrinkage
{shrink:.0f} pseudo-rounds, as chosen on validation) and `sigma` ({sigma:.3f} strokes) is the
residual round-to-round standard deviation estimated on each fold's training seasons. A cut is
applied after round 2. Win, top-10 and make-cut probabilities are the simulated frequency over
{config["sim"]["n_sims"]:,} tournaments. The main comparison below replays the real number of cut
survivors (`cut_mode="actual"`), which validates the round-score model on its own, separately from
the cut-size assumption a live forecast would need. Differences are model minus reference, so
**negative means better**. Intervals are 95% bootstrap intervals over events ({samples} resamples,
seed {seed}); differences against Baseline 1 use the same resampled events for both, so they are
paired.

## Walk-forward folds

{fold_lines}

## Results, pooled validation seasons

{results_table(rows, "pooled")}

## Speed check

{config["sim"]["n_sims"]:,} simulations of the largest validation-season field ({field_size}
players) took {seconds:.3f} seconds.

## Sensitivity to the cut assumption

`cut_mode="fraction"`, {config["sim"]["fallback_cut_fraction"]:.0%} of the field

For events without a known outcome, the cut has to be approximated. This shows the same simulator
with a fixed-fraction cutline instead of the real one, compared to the naive forecast (pooled
validation log loss; lower is better):

{fraction_table}

Calibration: `simulator_calibration.png` (pooled validation predictions, equal-frequency bins,
`cut_mode="actual"`).
"""


def main() -> None:
    config = load_config()
    validation = config["splits"]["validation_seasons"]
    seed, samples = config["evaluation"]["seed"], config["evaluation"]["bootstrap_samples"]

    events, rounds, folds = model1_run.load_inputs(config)
    half_life, shrink, _ = model1_run.tune_rating(events, rounds, folds, config["model1"], seed)
    features = model1_run.features_for(
        events, rounds, config["model1"]["rating"], half_life, shrink
    )

    baseline = model1_run.baseline_predictions(features, folds, config)
    model1 = {}
    rows = []
    for label in LABELS:
        kind, columns = ("softmax", WIN_COLUMNS) if label == "win" else ("logistic", FULL_COLUMNS)
        model1[label] = model1_predictions(
            features, label, kind, columns, folds, config["model1"], seed
        )
        rows += score_model(label, "Baseline 1", baseline[label], None, samples, seed)
        rows += score_model(label, "Model 1", model1[label], baseline[label], samples, seed)

    simulated = simulate_predictions(features, rounds, folds, config["sim"], "actual", seed)
    for label in LABELS:
        rows += score_model(label, "Simulator", simulated[label], baseline[label], samples, seed)

    fraction_simulated = simulate_predictions(
        features, rounds, folds, config["sim"], "fraction", seed
    )
    fraction_rows = []
    for label in LABELS:
        scored = score_model(
            label, "Simulator (fraction cut)", fraction_simulated[label], None, samples, seed
        )
        pooled = next(r for r in scored if r["slice"] == "pooled")
        fraction_rows.append({**pooled, "label_key": label})

    train_seasons, test_season = folds[-1]
    sigma = estimate_residual_sigma(
        features[features["season"].isin(train_seasons)],
        rounds[rounds["season"].isin(train_seasons)],
    )
    field_size, seconds = time_ten_thousand_sims(features[features["season"] == test_season], sigma)

    bins = config["evaluation"]["calibration_bins"]
    tables = {
        LABEL_NAMES[label]: {
            "Simulator": calibration_table(simulated[label]["y"], simulated[label]["p"], bins),
            "Baseline 1": calibration_table(baseline[label]["y"], baseline[label]["p"], bins),
            "Model 1": calibration_table(model1[label]["y"], model1[label]["p"], bins),
        }
        for label in LABELS
    }

    report_dir = Path(config["evaluation"]["report_dir"])
    report_dir.mkdir(parents=True, exist_ok=True)
    text = build_report(
        config, folds, half_life, shrink, rows, fraction_rows, field_size, seconds, sigma
    )
    (report_dir / "simulator_validation.md").write_text(text)
    pd.DataFrame(rows).to_csv(report_dir / "simulator_validation_metrics.csv", index=False)
    plot_calibration(
        tables,
        report_dir / "simulator_calibration.png",
        f"Simulator vs Baseline 1 vs Model 1 calibration, validation seasons {validation}",
    )
    print(text)


if __name__ == "__main__":
    main()
