"""One-time evaluation on the frozen 2025 holdout, agreed with the user on 2026-09-26.

Run with `uv run python -m src.models.run_holdout`. This is the single agreed look at the frozen
holdout season (see docs/DECISIONS.md): Baseline 1's window and Model 1's rating settings are
re-derived exactly as they were for the validation report (never re-tuned on the holdout), then
both models are refit on the training and validation seasons combined and evaluated once on the
holdout season. Nothing here may be changed after seeing these numbers.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from src.config import assert_no_forward_test, assert_no_holdout, load_config
from src.features.ratings import build_features
from src.models import run_baseline1 as baseline_run
from src.models import run_model1 as model1_run
from src.models.evaluation import calibration_table, plot_calibration, walk_forward_folds
from src.models.model1 import FULL_COLUMNS, WIN_COLUMNS
from src.models.model1 import walk_forward_predictions as model1_predictions
from src.models.reporting import LABEL_NAMES, results_table, score_model

LABELS = baseline_run.LABELS


def choose_settings(config: dict) -> tuple[float, float, dict[str, int]]:
    """Re-derive Model 1's rating settings and Baseline 1's window from the validation seasons.

    Restricted to seasons up to the last validation season, exactly as in the validation report,
    so this never looks at the holdout or forward-test seasons even if they are present in the
    input files.
    """
    splits = config["splits"]
    events = baseline_run.load_events(config["data"]["events_history"])
    rounds = pd.read_csv(config["data"]["rounds_history"])
    folds = walk_forward_folds(
        events["season"].unique(), splits["validation_seasons"], splits["first_train_season"]
    )
    last_validation = max(test for _, test in folds)
    events = events[events["season"] <= last_validation]
    rounds = rounds[rounds["season"] <= last_validation]
    assert_no_holdout(config, events["season"].unique())

    half_life, shrink, _ = model1_run.tune_rating(
        events, rounds, folds, config["model1"], config["evaluation"]["seed"]
    )
    windows = model1_run.chosen_baseline_windows(events, folds, config)
    return half_life, shrink, windows


def build_report(config, holdout_season, train_seasons, half_life, shrink, windows, rows) -> str:
    samples, seed = config["evaluation"]["bootstrap_samples"], config["evaluation"]["seed"]
    windows_line = ", ".join(f"{LABEL_NAMES[label]}: {windows[label]}-season" for label in LABELS)
    return f"""# Frozen holdout report: season {holdout_season}

Generated by `uv run python -m src.models.run_holdout` from `config/config.yaml`. **This is the
one agreed look at the frozen {holdout_season} holdout** (see docs/DECISIONS.md), taken after
Baseline 1 and Model 1 were finalised on the 2023-2024 validation seasons. Nothing was tuned,
selected or changed after seeing these numbers.

Both models are refit on seasons {train_seasons} (training plus validation combined) using the
settings already chosen on validation: Baseline 1's rolling-strokes-gained window per label
({windows_line}); Model 1's rating half-life {half_life:.0f} days and shrinkage {shrink:.0f}
pseudo-rounds. Differences are model minus reference, so **negative means better**. Intervals are
95% bootstrap intervals over events ({samples} resamples, seed {seed}); differences against
Baseline 1 use the same resampled events for both, so they are paired.

## Results, holdout season {holdout_season}

{results_table(rows, "pooled")}

## Players with rating history only

{results_table(rows, "pooled, players with rating history")}

Calibration: `holdout_2025_calibration.png`.
"""


def main() -> None:
    config = load_config()
    seed, samples = config["evaluation"]["seed"], config["evaluation"]["bootstrap_samples"]
    splits = config["splits"]
    (holdout_season,) = splits["holdout_seasons"]
    train_seasons = list(range(splits["first_train_season"], holdout_season))
    holdout_fold = [(train_seasons, holdout_season)]
    assert_no_forward_test(config, [*train_seasons, holdout_season])

    half_life, shrink, windows = choose_settings(config)
    print(
        f"Settings re-derived from validation: half-life {half_life:.0f} days, "
        f"shrinkage {shrink:.0f} rounds, windows {windows} "
        "(should match reports/model1_validation.md)"
    )

    events = baseline_run.load_events(config["data"]["events_history"])
    rounds = pd.read_csv(config["data"]["rounds_history"])
    features = build_features(
        events, rounds, half_life, config["model1"]["rating"]["short_half_life_days"], shrink
    )

    baseline, model, rows = {}, {}, []
    for label in LABELS:
        column = baseline_run.window_column(config["baseline1"]["feature"], windows[label])
        baseline[label] = baseline_run.walk_forward_predictions(events, label, column, holdout_fold)
        rows += score_model(label, "Baseline 1", baseline[label], None, samples, seed)

        kind, columns = ("softmax", WIN_COLUMNS) if label == "win" else ("logistic", FULL_COLUMNS)
        model[label] = model1_predictions(
            features, label, kind, columns, holdout_fold, config["model1"], seed
        )
        rows += score_model(label, "Model 1", model[label], baseline[label], samples, seed)

        if label != "win":
            boosting = model1_predictions(
                features, label, "boosting", FULL_COLUMNS, holdout_fold, config["model1"], seed
            )
            rows += score_model(label, "Model 1 boosting", boosting, baseline[label], samples, seed)

    bins = config["evaluation"]["calibration_bins"]
    tables = {
        LABEL_NAMES[label]: {
            "Model 1": calibration_table(model[label]["y"], model[label]["p"], bins),
            "Baseline 1": calibration_table(baseline[label]["y"], baseline[label]["p"], bins),
        }
        for label in LABELS
    }

    report_dir = Path(config["evaluation"]["report_dir"])
    report_dir.mkdir(parents=True, exist_ok=True)
    text = build_report(config, holdout_season, train_seasons, half_life, shrink, windows, rows)
    (report_dir / "holdout_2025_results.md").write_text(text)
    pd.DataFrame(rows).to_csv(report_dir / "holdout_2025_metrics.csv", index=False)
    plot_calibration(
        tables,
        report_dir / "holdout_2025_calibration.png",
        f"Model 1 vs Baseline 1 calibration, frozen holdout season {holdout_season}",
    )
    print(text)


if __name__ == "__main__":
    main()
