"""Ongoing forward test on the in-progress 2026 season.

Run with `uv run python -m src.models.run_forward_test`. Unlike the frozen 2025 holdout
(`src/models/run_holdout.py`), this is meant to be re-run repeatedly as more 2026 events finish -
it is not a one-look evaluation, so nothing here restricts re-running it. What *is* frozen: Model
1's rating settings and Baseline 1's window, re-derived (never re-tuned) from the 2023-2024
validation seasons, exactly as in the validation and holdout reports (`run_holdout.choose_settings`
is reused unchanged). The 2025 season, already reported as the frozen holdout, is folded into
training here: once its one look has been taken and reported, using its rounds as historical input
for predicting a later season is ordinary walk-forward progression, not a new look at anything held
out. See docs/DECISIONS.md.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from src.config import load_config
from src.features.ratings import build_features
from src.models import run_baseline1 as baseline_run
from src.models import run_holdout as holdout_run
from src.models.evaluation import calibration_table, plot_calibration
from src.models.model1 import FULL_COLUMNS, WIN_COLUMNS
from src.models.model1 import walk_forward_predictions as model1_predictions
from src.models.reporting import LABEL_NAMES, align_has_history, results_table, score_model
from src.sim.run_simulator import fold_sigmas, simulate_predictions

LABELS = baseline_run.LABELS


def load_forward_inputs(config: dict) -> tuple[pd.DataFrame, pd.DataFrame, list]:
    """Events/rounds through the forward-test season, and its single (train, test) fold.

    Training uses every earlier season, including the now-reported holdout season, so the model
    predicting 2026 is fit on the same history a live forecast would actually have.
    """
    splits = config["splits"]
    (forward_season,) = splits["forward_test_seasons"]
    events = pd.concat(
        [
            baseline_run.load_events(config["data"]["events_history"]),
            baseline_run.load_events(config["data"]["events_2026"]),
        ],
        ignore_index=True,
    )
    rounds = pd.concat(
        [
            pd.read_csv(config["data"]["rounds_history"]),
            pd.read_csv(config["data"]["rounds_2026"]),
        ],
        ignore_index=True,
    )
    train_seasons = list(range(splits["first_train_season"], forward_season))
    fold = [(train_seasons, forward_season)]
    return events, rounds, fold


def build_report(
    config, forward_season, train_seasons, half_life, shrink, windows, rows, n_events
) -> str:
    samples, seed = config["evaluation"]["bootstrap_samples"], config["evaluation"]["seed"]
    windows_line = ", ".join(f"{LABEL_NAMES[label]}: {windows[label]}-season" for label in LABELS)
    return f"""# Forward test: season {forward_season} (in progress, updated as events finish)

Generated by `uv run python -m src.models.run_forward_test` from `config/config.yaml`.
**This is not a frozen evaluation.** It is re-run as more of the {forward_season} season finishes;
today it covers {n_events} completed events. Settings are re-derived (never re-tuned) from the
2023-2024 validation seasons, identically to `reports/holdout_2025_results.md`: Baseline 1's
rolling-strokes-gained window per label ({windows_line}); Model 1's rating half-life
{half_life:.0f} days and shrinkage {shrink:.0f} pseudo-rounds. Both models are refit on seasons
{train_seasons} (everything through the frozen 2025 holdout, now historical training data) and
scored on the {forward_season} events finished so far. Differences are model minus reference, so
**negative means better**. Intervals are 95% bootstrap intervals over events ({samples} resamples,
seed {seed}); differences against Baseline 1 use the same resampled events for both, so they are
paired. Sample size is small and grows through the season - read the intervals, not just the point
estimates.

## Results, {forward_season} events so far

{results_table(rows, "pooled")}

## Players with rating history only

{results_table(rows, "pooled, players with rating history")}

Calibration: `forward_test_2026_calibration.png`.
"""


def main() -> None:
    config = load_config()
    seed, samples = config["evaluation"]["seed"], config["evaluation"]["bootstrap_samples"]
    (forward_season,) = config["splits"]["forward_test_seasons"]

    half_life, shrink, windows = holdout_run.choose_settings(config)
    print(
        f"Settings re-derived from validation: half-life {half_life:.0f} days, "
        f"shrinkage {shrink:.0f} rounds, windows {windows} "
        "(should match reports/model1_validation.md)"
    )

    events, rounds, fold = load_forward_inputs(config)
    train_seasons, _ = fold[0]
    features = build_features(
        events, rounds, half_life, config["model1"]["rating"]["short_half_life_days"], shrink
    )
    sigmas = fold_sigmas(features, rounds, fold)

    baseline, model, rows = {}, {}, []
    for label in LABELS:
        column = baseline_run.window_column(config["baseline1"]["feature"], windows[label])
        baseline[label] = align_has_history(
            baseline_run.walk_forward_predictions(events, label, column, fold), features
        )
        rows += score_model(label, "Baseline 1", baseline[label], None, samples, seed)

        kind, columns = ("softmax", WIN_COLUMNS) if label == "win" else ("logistic", FULL_COLUMNS)
        model[label] = model1_predictions(
            features, label, kind, columns, fold, config["model1"], seed
        )
        rows += score_model(label, "Model 1", model[label], baseline[label], samples, seed)

    simulated = simulate_predictions(features, fold, sigmas, config["sim"], "fraction", seed)
    for label in LABELS:
        rows += score_model(label, "Simulator", simulated[label], baseline[label], samples, seed)

    n_events = int(features[features["season"] == forward_season]["tournament_id"].nunique())

    bins = config["evaluation"]["calibration_bins"]
    tables = {
        LABEL_NAMES[label]: {
            "Model 1": calibration_table(model[label]["y"], model[label]["p"], bins),
            "Baseline 1": calibration_table(baseline[label]["y"], baseline[label]["p"], bins),
            "Simulator": calibration_table(simulated[label]["y"], simulated[label]["p"], bins),
        }
        for label in LABELS
    }

    report_dir = Path(config["evaluation"]["report_dir"])
    report_dir.mkdir(parents=True, exist_ok=True)
    text = build_report(
        config, forward_season, train_seasons, half_life, shrink, windows, rows, n_events
    )
    (report_dir / "forward_test_2026_results.md").write_text(text)
    pd.DataFrame(rows).to_csv(report_dir / "forward_test_2026_metrics.csv", index=False)
    plot_calibration(
        tables,
        report_dir / "forward_test_2026_calibration.png",
        f"Model 1 vs Baseline 1 vs Simulator calibration, forward test season {forward_season}"
        f" ({n_events} events so far)",
    )
    print(text)


if __name__ == "__main__":
    main()
